///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class autowinnerModel {
/*
{
  "status": true,
  "message": "Success",
  "data": "B"
} 
*/

  bool? status;
  String? message;
  String? data;

  autowinnerModel({
    this.status,
    this.message,
    this.data,
  });
  autowinnerModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = json['data']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['data'] = this.data;
    return data;
  }
}
